# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 597586ca6c37721742e5be8404c850be1465a4811226ceb130b4f4a91dcc013c978ed0326a8345456126b6b25a092fb2a6fe81c766405634344644bf05a7b760

test:
  secret_key_base: e77b0ae456c455e665734f8a3537dcfcc5dea30b175901cb824df36f84e545def945852065bf0583ae358d98d8b77883f2de5f23da550449384c19a8f285e319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
